name: phishti_detector
description: A Flutter app for proactive SMS phishing detection using ML
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # UI & Navigation
  cupertino_icons: ^1.0.2
  go_router: ^12.1.3
  flutter_svg: ^2.0.9
  lottie: ^2.7.0
  
  # State Management
  provider: ^6.1.1
  riverpod: ^2.4.9
  flutter_riverpod: ^2.4.9
  
  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_messaging: ^14.7.10
  
  # ML & TensorFlow Lite
  tflite_flutter: ^0.10.4
  tflite_flutter_helper: ^0.3.1
  
  # Local Storage & Encryption
  sqflite: ^2.3.0
  sqlcipher_flutter_libs: ^0.5.0
  sqflite_sqlcipher: ^2.3.0
  shared_preferences: ^2.2.2
  
  # SMS & Permissions
  sms_advanced: ^0.2.0
  permission_handler: ^11.1.0
  device_info_plus: ^9.1.1
  
  # Network & HTTP
  http: ^1.1.2
  dio: ^5.4.0
  
  # Utilities
  crypto: ^3.0.3
  uuid: ^4.2.1
  intl: ^0.19.0
  url_launcher: ^6.2.2
  
  # Security
  encrypt: ^5.0.1
  flutter_secure_storage: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/models/
    - assets/images/
    - assets/animations/
  
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
