name: phishti_detector
description: A Flutter app for proactive SMS phishing detection using ML
version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # UI & Navigation
  cupertino_icons: ^1.0.2
  go_router: ^12.1.3
  
  # State Management
  provider: ^6.1.1
  riverpod: ^2.4.9
  flutter_riverpod: ^2.4.9
  
  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_messaging: ^15.1.3
  
  # Authentication
  google_sign_in: ^6.1.6
  
  # Storage & Database
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  flutter_secure_storage: ^9.0.0
  
  # Permissions & Device
  permission_handler: ^11.2.0
  device_info_plus: ^9.1.1
  local_auth: ^2.1.6
  image_picker: ^1.0.4
  
  # Notifications
  flutter_local_notifications: ^17.2.3
  
  # Network & HTTP
  http: ^1.1.2
  connectivity_plus: ^5.0.2
  
  # Utilities
  crypto: ^3.0.3
  uuid: ^4.2.1
  intl: ^0.19.0
  url_launcher: ^6.2.2
  path_provider: ^2.1.2
  
  # Encryption & Serialization
  encrypt: ^5.0.1
  json_annotation: ^4.9.0
  
  # Compatibility & Performance
  flutter_screenutil: ^5.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  
  # Code generation
  build_runner: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
